-- MySQL Script generated by MySQL Workbench
-- Fri Apr  3 12:19:48 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`offers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`offers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL NOT NULL,
  `category` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `offer_id_UNIQUE` (`id` ASC),
  INDEX `fk_offers_categories_idx` (`category` ASC),
  CONSTRAINT `fk_offers_categories`
    FOREIGN KEY (`category`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NULL,
  `surname` VARCHAR(50) NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ratings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `offer` INT NOT NULL,
  `rating` INT NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ratings_users1_idx` (`user` ASC),
  INDEX `fk_ratings_offers1_idx` (`offer` ASC),
  CONSTRAINT `fk_ratings_users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_offers1`
    FOREIGN KEY (`offer`)
    REFERENCES `mydb`.`offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sales_orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sales_orders` (
  `id` INT NOT NULL,
  `user` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_orders_users1_idx` (`user` ASC),
  CONSTRAINT `fk_sales_orders_users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales_order_entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sales_order_entries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sales_order_entries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sales_order` INT NOT NULL,
  `offer` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_sales_order_entries_offers1_idx` (`offer` ASC),
  INDEX `fk_sales_order_entries_sales_orders1_idx` (`sales_order` ASC),
  CONSTRAINT `fk_sales_order_entries_offers1`
    FOREIGN KEY (`offer`)
    REFERENCES `mydb`.`offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_order_entries_sales_orders1`
    FOREIGN KEY (`sales_order`)
    REFERENCES `mydb`.`sales_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
