-- MySQL Script generated by MySQL Workbench
-- 04/25/15 16:59:49
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema online-store
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `online-store` ;

-- -----------------------------------------------------
-- Schema online-store
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`categories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-store`.`offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`offers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` DECIMAL NOT NULL,
  `category` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `offer_id_UNIQUE` (`id` ASC),
  INDEX `fk_offers_categories_idx` (`category` ASC),
  CONSTRAINT `fk_offers_categories`
    FOREIGN KEY (`category`)
    REFERENCES `online-store`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-store`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `name` VARCHAR(50) NULL,
  `surname` VARCHAR(50) NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-store`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`ratings` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user` INT NOT NULL,
  `offer` INT NOT NULL,
  `rating` INT NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_ratings_users1_idx` (`user` ASC),
  INDEX `fk_ratings_offers1_idx` (`offer` ASC),
  CONSTRAINT `fk_ratings_users1`
    FOREIGN KEY (`user`)
    REFERENCES `online-store`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_offers1`
    FOREIGN KEY (`offer`)
    REFERENCES `online-store`.`offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-store`.`sales_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`sales_orders` (
  `id` BIGINT NOT NULL,
  `user` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_orders_users1_idx` (`user` ASC),
  CONSTRAINT `fk_sales_orders_users1`
    FOREIGN KEY (`user`)
    REFERENCES `online-store`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online-store`.`sales_order_entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online-store`.`sales_order_entries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `sales_order` INT NOT NULL,
  `offer` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_sales_order_entries_offers1_idx` (`offer` ASC),
  INDEX `fk_sales_order_entries_sales_orders1_idx` (`sales_order` ASC),
  CONSTRAINT `fk_sales_order_entries_offers1`
    FOREIGN KEY (`offer`)
    REFERENCES `online-store`.`offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_order_entries_sales_orders1`
    FOREIGN KEY (`sales_order`)
    REFERENCES `online-store`.`sales_orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
